FROM ubuntu:22.04

RUN apt update && apt full-upgrade -y \
    python3 \
    python3-pip
    
COPY requirements.txt /var/app/requirements.txt

RUN apt install default-libmysqlclient-dev -y

WORKDIR /var/app

RUN pip3 install -r requirements.txt

COPY ./app /var/app

ENTRYPOINT ["./run.sh"]