# Generated by Django 4.1 on 2023-10-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='repository',
            table='repositories',
        ),
    ]
