# Generated by Django 4.1 on 2023-10-07 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RUserRepositoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_property', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'r_user_repository_members',
                'verbose_name_plural': 'r_user_repository_members',
                'db_table': 'r_user_repository_member',
            },
        ),
        migrations.AddField(
            model_name='repository',
            name='likes',
            field=models.ManyToManyField(related_name='liked_repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repository',
            name='members',
            field=models.ManyToManyField(related_name='member_repositories', through='seekosApi.RUserRepositoryMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repository',
            name='phases',
            field=models.CharField(choices=[('init', 'Init'), ('development', 'Development'), ('test', 'Test'), ('concluded', 'Concluded')], default='init', max_length=100),
        ),
        migrations.AddField(
            model_name='ruserrepositorymember',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seekosApi.repository'),
        ),
        migrations.AddField(
            model_name='ruserrepositorymember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
