# Generated by Django 4.1 on 2023-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0002_alter_repository_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(choices=[('texto', 'TEXTO'), ('corpo', 'CORPO')], max_length=100),
        ),
    ]
