# Generated by Django 4.1 on 2023-10-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0003_alter_repository_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='description',
            new_name='resume',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='language',
        ),
        migrations.AddField(
            model_name='repository',
            name='body',
            field=models.TextField(default='Default Body Text'),
        ),
        migrations.AddField(
            model_name='repository',
            name='ranking',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='repository',
            name='type',
            field=models.CharField(choices=[('idea', 'Idea'), ('project', 'Project')], default='idea', max_length=100),
        ),
    ]
