# Generated by Django 4.1 on 2023-10-08 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0004_repositorycomment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='phases',
        ),
        migrations.AddField(
            model_name='repository',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('development', 'Development'), ('test', 'Test'), ('concluded', 'Concluded')], default='init', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='url_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='url_project',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='body',
            field=models.TextField(blank=True, default='Default Body Text', null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='keys',
            field=models.ManyToManyField(blank=True, null=True, related_name='keys_repositories', to='seekosApi.keys'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_repositories', to=settings.AUTH_USER_MODEL),
        ),
    ]
