# Generated by Django 4.1 on 2023-10-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0004_rename_description_repository_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='url',
        ),
        migrations.AddField(
            model_name='repository',
            name='phases',
            field=models.CharField(choices=[('init', 'Idea'), ('development', 'Development'), ('development', 'Development'), ('test', 'Test'), ('concluded', 'Concluded')], default='init', max_length=100),
        ),
    ]
