# Generated by Django 4.1 on 2023-10-08 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0005_remove_repository_phases_repository_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='keys',
        ),
        migrations.AlterField(
            model_name='repository',
            name='likes',
            field=models.ManyToManyField(related_name='liked_repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repository',
            name='resume',
            field=models.CharField(max_length=250),
        ),
    ]
