# Generated by Django 4.1 on 2023-10-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0005_remove_repository_url_repository_phases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='phases',
            field=models.CharField(choices=[('init', 'Idea'), ('development', 'Development'), ('test', 'Test'), ('concluded', 'Concluded')], default='init', max_length=100),
        ),
        migrations.AlterModelTable(
            name='repository',
            table='repository',
        ),
        migrations.CreateModel(
            name='RepositoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seekosApi.repository')),
            ],
            options={
                'db_table': 'repository_comment',
            },
        ),
    ]
