# Generated by Django 4.1 on 2023-10-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekosApi', '0006_remove_repository_keys_alter_repository_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='keys',
            field=models.ManyToManyField(related_name='keys_repositories', to='seekosApi.keys'),
        ),
    ]
